version: '2'
services:
  ide:
    image: docker.io/psharkey/intellij:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:
    build: 
      context: .
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
