name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag novnc:test

    - name: Run the Docker container
      run: |
        docker run -d -p 8080:8080 novnc:test

    - name: Wait for container to start
      run: sleep 10

    - name: Check noVNC
      run: curl --retry 10 --retry-delay 5 --retry-connrefused "http://localhost:8080"
